### ISSUE TITLE
Not initializing 

### ISSUE THREAD

**Issue by rlilbun10** [tin537/AStools#2]
Hello I have installed the module through lsposed and enabled , also I have installed the APK but whenever I open the application it's comes up black screen that says "Hello Android Security Tools loaded from lsposed" that's it. 
I wait for any change and it doesn't seem to, I have gone through the scoping for this module and can't figure it out. I'm sure it's on me that I'm not setting something up correctly but there are no clear instructions and yes I'm sorta a noob so I can't figure out what the issue is. Any help is appreciated 
![Screenshot_2024-04-26-19-44-55-35_134442efa1acc064b9b1177e38cae243](https://github.com/tin537/AStools/assets/70468022/47a0f24d-8a32-402c-b2b5-f9988c59ae3d)

**Comment by tin537** [comment]
result of hooking view show on android logcat
